#version 450

layout(local_size_x = 32,  local_size_y = 32) in;

layout(rgba8, binding = 0) writeonly uniform image2D frame;


void main() {
    uvec2 resolution = imageSize(frame);
    uvec2 pixel = gl_GlobalInvocationID.xy;

    if (pixel.x >= resolution.x || pixel.y >= resolution.y)
        return;

    vec2 uv = vec2(pixel) / vec2(resolution);
    imageStore(frame, ivec2(pixel), vec4(uv, 0.0, 1.0));

}

